# Generated by Django 4.1 on 2024-11-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Contrato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha de Creación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
        ),
    ]
