# Generated by Django 4.1 on 2024-11-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='actualizado_en',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
