# Generated by Django 4.2.7 on 2025-10-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0003_carrito_coleccionable_itemcarrito_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
