# Generated by Django 4.2.7 on 2025-10-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0004_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coleccionable',
            old_name='tipo_fungo',
            new_name='tipo_coleccionable',
        ),
    ]
