# Generated by Django 4.2.7 on 2025-10-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0005_rename_tipo_fungo_coleccionable_tipo_coleccionable'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccionable',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], default='disponible', max_length=20),
        ),
    ]
