# Generated by Django 4.2.7 on 2025-10-16 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0006_coleccionable_estado_videojuego_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad_comprada', models.IntegerField()),
                ('proveedor', models.CharField(max_length=200)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('coleccionable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eva_3.coleccionable')),
                ('videojuego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eva_3.videojuego')),
            ],
        ),
    ]
