# Generated by Django 4.2.7 on 2025-10-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0009_pedido_fecha_actualizacion_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccionable',
            name='badge',
            field=models.CharField(blank=True, choices=[('best-seller', 'Más Vendido'), ('new-release', 'Nuevo Lanzamiento'), ('special-offer', 'Oferta Especial'), ('low-stock', 'A Punto de Irse'), ('', 'Sin Badge')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='badge',
            field=models.CharField(blank=True, choices=[('best-seller', 'Más Vendido'), ('new-release', 'Nuevo Lanzamiento'), ('special-offer', 'Oferta Especial'), ('low-stock', 'A Punto de Irse'), ('', 'Sin Badge')], default='', max_length=20),
        ),
    ]
