# Generated by Django 4.2.7 on 2025-10-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0010_coleccionable_badge_videojuego_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccionable',
            name='imagen_recomendada',
            field=models.ImageField(blank=True, help_text='Imagen específica para mostrar en recomendados', null=True, upload_to='recomendados/coleccionables/'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen_recomendada',
            field=models.ImageField(blank=True, help_text='Imagen específica para mostrar en recomendados', null=True, upload_to='recomendados/videojuegos/'),
        ),
    ]
