# Generated by Django 4.2.7 on 2025-10-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0011_coleccionable_imagen_recomendada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccionable',
            name='es_recomendado',
            field=models.BooleanField(default=False),
        ),
    ]
