# Generated by Django 4.2.7 on 2025-10-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0012_coleccionable_es_recomendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='numero_encargo',
            field=models.CharField(blank=True, help_text='Número de encargo o referencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='numero_encargo',
            field=models.CharField(blank=True, help_text='Número de encargo o referencia', max_length=100, null=True),
        ),
    ]
