# Generated by Django 4.2.7 on 2025-10-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0015_remove_facturacompra_numero_encargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaventa',
            name='numero_encargo',
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='coleccionable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eva_3.coleccionable'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='videojuego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eva_3.videojuego'),
        ),
    ]
