# Generated by Django 4.2.7 on 2025-10-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0016_remove_facturaventa_numero_encargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='codigo_paquete',
            field=models.CharField(blank=True, help_text='Código de identificación del paquete o lote', max_length=100),
        ),
    ]
