# Generated by Django 4.1 on 2025-10-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0017_facturacompra_codigo_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
