# Generated by Django 5.0.6 on 2025-11-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_3', '0018_usuario_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaRegalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tarjetas_regalo/')),
                ('tipo_tarjeta', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('es_recomendado', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, choices=[('best-seller', 'Más Vendido'), ('new-release', 'Nuevo Lanzamiento'), ('special-offer', 'Oferta Especial'), ('low-stock', 'A Punto de Irse'), ('', 'Sin Badge')], default='', max_length=20)),
                ('imagen_recomendada', models.ImageField(blank=True, help_text='Imagen específica para mostrar en recomendados', null=True, upload_to='recomendados/tarjetas_regalo/')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='coleccionable',
        ),
        migrations.RemoveField(
            model_name='facturacompra',
            name='coleccionable',
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='tarjeta_regalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eva_3.tarjetaregalo'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='tarjeta_regalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eva_3.tarjetaregalo'),
        ),
        migrations.DeleteModel(
            name='Coleccionable',
        ),
    ]
